server:
  port: 8080
  context-path: /todo

security:
  ignored: /swagger-resources/**

info:
  app:
    name: TODO Checklist
    description: Backend Layer TODO Checklist
    version: 1.0
    
endpoint:
  base: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: password