server:
  port: 8080
  servlet:
    context-path: /todo

info:
  app:
    name: TODO Checklist
    description: Backend Layer TODO Checklist
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: heapdump,threaddump,info,metrics,health
  server:
    port: 8081

endpoint:
  base: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker.for.mac.localhost:3306/todo
    username: root
    password: password